import Testing
import Foundation
@testable import CLMServer

// Fixtures generated by Python (clm_mlx.schema) so the Swift port is pinned
// to upstream byte-for-byte.
struct SchemaParityTests {
    let fixtures: OrderedObject

    init() throws {
        let url = Bundle.module.url(forResource: "schema-fixtures", withExtension: "json")
            ?? Bundle.module.url(
                forResource: "schema-fixtures", withExtension: "json", subdirectory: "CLMServerTests_Fixtures")
            ?? Bundle.module.url(
                forResource: "schema-fixtures", withExtension: "json", subdirectory: "Fixtures")
        guard let url else { throw JSONError("fixtures not found") }
        let text = try String(contentsOf: url, encoding: .utf8)
        guard case .object(let o) = try JSONParser.parse(text) else {
            throw JSONError("invalid fixtures")
        }
        fixtures = o
    }

    @Test func toTextMatchesPython() throws {
        guard case .array(let cases)? = fixtures["to_text"] else { Issue.record("fixtures missing"); return }
        for entry in cases {
            let name = entry[0]?.stringValue ?? "?"
            let input = entry[1] ?? .null
            let expected = entry[2]?.stringValue ?? ""
            #expect(Schema.toText(input) == expected)
        }
    }

    @Test func candidatesMatchPython() throws {
        guard case .array(let cases)? = fixtures["candidates"] else { Issue.record("fixtures missing"); return }
        for entry in cases {
            let name = entry[0]?.stringValue ?? "?"
            let question = entry[1] ?? .null
            let expected = entry[2] ?? .null
            let got = try Schema.candidates(question)
            // python tuple -> JSON array [keys, texts]
            guard case .array(let pair) = expected else { Issue.record("bad fixture"); continue }
            #expect(got.keys == pair[0].arrayValue)
            #expect(got.texts == pair[1].arrayValue)
        }
    }

    @Test func stateTextMatchesPython() throws {
        guard case .array(let cases)? = fixtures["state_text"] else { Issue.record("fixtures missing"); return }
        for entry in cases {
            guard case .array(let parts) = entry else { continue }
            // parts: [state repr, instructions (or null), expected text]
            let state: JSONValue
            switch parts[0] {
            case .string(let lit): state = parsePythonLiteral(lit)
            case let v: state = v
            }
            let expected = parts[2].stringValue ?? ""
            #expect(Schema.stateText(state, parts[1]) == expected)
        }
    }

    /// Same shape as the generator's QUESTIONS["choice"].
    static let choiceQuestion = JSONValue.object(OrderedObject([
        ("type", .string("choice")),
        ("instructions", .string("Pick")),
        ("criteria", .object(OrderedObject([
            ("a", .string("Option A")),
            ("b", .string("")),
            ("c", .int(3)),
            ("d", .null),
        ]))),
    ]))

    @Test func buildPairsMatchesPython() throws {
        guard case .object(let pairs)? = fixtures["build_pairs"] else { Issue.record("fixtures missing"); return }
        let questions = OrderedObject([
            ("noul_default", JSONValue.object(OrderedObject([
                ("type", .string("noul")),
                ("instructions", .string("Is this urgent?")),
            ]))),
            ("choice", Self.choiceQuestion),
            ("score", JSONValue.object(OrderedObject([
                ("type", .string("score")),
                ("criteria", .array([.int(1), .int(2), .int(3)])),
            ]))),
        ])
        let got = try Schema.buildPairs(
            state: .object(OrderedObject([("issue", .string("double charge"))])),
            questions: questions)
        #expect(got.map(\.qid) == ["noul_default", "choice", "score"])
        for pair in got {
            guard case .array(let expected) = pairs[pair.qid] ?? .null else { continue }
            #expect(pair.stateText == expected[0].stringValue)
            #expect(pair.keys == expected[1].arrayValue)
            #expect(pair.texts == expected[2].arrayValue)
        }
    }

    @Test func softmaxConfidenceAnswersMatchPython() throws {
        guard case .array(let softmax)? = fixtures["softmax"] else { Issue.record("fixtures missing"); return }
        let inputs: [[Double]] = [[0.1, 0.2, 0.3], [100.0, 100.0], [-5.0]]
        for (i, caseRef) in softmax.enumerated() {
            let got = Schema.softmax(inputs[i])
            let expected: [Double]
            if case .array(let items) = caseRef { expected = items.compactMap { $0.doubleValue } } else { expected = [] }
            #expect(got.count == expected.count)
            for (a, b) in zip(got, expected) where abs(a - b) > 1e-12 {
                Issue.record("softmax[\(i)] \(a) != \(b)")
            }
        }
        guard case .array(let confidence)? = fixtures["confidence"] else { Issue.record("fixtures missing"); return }
        let confInputs: [[Double]] = [[0.6, 0.4], [0.5, 0.5], [1.0], [0.7, 0.2, 0.1]]
        for (i, caseRef) in confidence.enumerated() {
            let expected = caseRef.doubleValue ?? 0
            #expect(abs(Schema.confidence(confInputs[i]) - expected) < 1e-12)
        }

        // answer assembly: serialize ours and compare to python's JSON text
        guard case .object(let choiceAns)? = fixtures["answer_choice"] else { Issue.record("fixtures missing"); return }
        let probs = Schema.softmax([1.0, 2.0, 0.5])
        let got = Schema.answerFromProbs(q: Self.choiceQuestion, keys: ["a", "b", "c"], probs: probs)
        let gotText = try JSONSerializer.serialize(got)
        let expectedText = try JSONSerializer.serialize(JSONValue.object(choiceAns))
        #expect(gotText == expectedText)
    }

    /// The fixture stores states as python reprs; decode the four shapes it uses.
    func parsePythonLiteral(_ s: String) -> JSONValue {
        switch s {
        case "None": return .null
        case "3.5": return .double(3.5)
        case "{'k': 'v'}":
            return .object(OrderedObject([("k", .string("v"))]))
        default:
            if s.hasPrefix("'"), s.hasSuffix("'") {
                return .string(String(s.dropFirst().dropLast()))
            }
            return .string(s)
        }
    }
}
