import Foundation
import MLX

/// Parity verification against the Python engine's reference outputs
/// (`test/fixtures/native-parity-reference.json`, generated by
/// `gen-parity-reference.py` from the same model snapshot).
///
/// Exits 0 when every check passes, 1 otherwise. Thresholds reflect that
/// Swift and Python bind the same MLX kernels; only kernel-level batching
/// and mask-path differences should remain.
func runParity(referencePath: String, modelDir: URL, truncation: String) async throws -> Int32 {
    let referenceText = try String(contentsOfFile: referencePath, encoding: .utf8)
    let reference = try JSONParser.parse(referenceText)
    guard case .object(let inputs) = reference["inputs"],
          case .object(let states) = inputs["states"],
          case .object(let questions) = inputs["questions"]
    else {
        FileHandle.standardError.write(Data("parity: invalid reference inputs\n".utf8))
        return 1
    }

    var failures: [String] = []
    var checks = 0

    func check(_ name: String, _ condition: Bool, _ detail: String = "") {
        checks += 1
        if !condition {
            failures.append(name + (detail.isEmpty ? "" : " (\(detail))"))
        }
    }

    let loadStart = Date()
    let engine = try await CLMEngine(modelDir: modelDir, cacheSize: 4096, truncation: truncation)
    let loadSeconds = Date().timeIntervalSince(loadStart)
    print(String(format: "engine loaded in %.1fs", loadSeconds))

    // heads scale
    if case .object(let headsRef)? = reference["heads"],
       case .double(let scaleRef)? = headsRef["scale"]
    {
        check("heads.scale", Float(scaleRef) == engine.heads.scale,
              "ref \(scaleRef) vs \(engine.heads.scale)")
    }

    // --- 1. schema texts (exact string parity)
    if case .object(let schemaRef)? = reference["schema"] {
        for tag in ["plain", "nested", "bare"] {
            guard case .object(let qs)? = schemaRef[tag] else { continue }
            let pairs = try Schema.buildPairs(state: states[tag]!, questions: questions)
            check("schema.\(tag).count", pairs.count == qs.count)
            for pair in pairs {
                guard case .object(let expected)? = qs[pair.qid] else { continue }
                check("schema.\(tag).\(pair.qid).state_text",
                      pair.stateText == expected["state_text"]!.stringValue)
                check("schema.\(tag).\(pair.qid).keys",
                      pair.keys == expected["keys"]!.arrayValue)
                check("schema.\(tag).\(pair.qid).texts",
                      pair.texts == expected["texts"]!.arrayValue)
            }
        }
        // long state: compare only length + head slice to keep the fixture small
        if let longText = inputs["long"]?.stringValue,
           case .object(let qs)? = schemaRef["long"],
           case .object(let expected)? = qs["urgent"]
        {
            let pairs = try Schema.buildPairs(
                state: .string(longText),
                questions: OrderedObject([("urgent", questions["urgent"]!)]))
            let st = pairs[0].stateText
            check("schema.long.len", st.count == expected["state_text_len"]?.intValue,
                  "\(st.count) vs \(expected["state_text_len"]?.intValue ?? -1)")
            check("schema.long.head",
                  String(st.prefix(120)) == expected["state_text_head"]!.stringValue)
        }
    }

    // --- 2. tokenizer ids (exact)
    if case .object(let tokRef)? = reference["tokenizer"] {
        for (text, sketchRef) in tokRef.pairs {
            guard case .object(let sketch) = sketchRef else { continue }
            let ids = engine.ids(text)
            check("tokenizer.len[\(preview(text))]",
                  ids.count == sketch["length"]!.intValue,
                  "\(ids.count) vs \(sketch["length"]!.intValue ?? -1)")
            // <=64 ids are stored in full under "head"; longer texts keep 24+24.
            let headRef = sketch["head"]!.intArrayValue ?? []
            if let tailRef = sketch["tail"]?.intArrayValue {
                check("tokenizer.head[\(preview(text))]", Array(ids.prefix(24)) == headRef)
                check("tokenizer.tail[\(preview(text))]", Array(ids.suffix(24)) == tailRef)
            } else {
                check("tokenizer.ids[\(preview(text))]", ids == headRef)
            }
        }
    }
    if case .object(let longSketch)? = reference[truncation == "head" ? "tokenizer_long_head" : "tokenizer_long_tail"],
       let longText = inputs["long"]?.stringValue,
       let urgentInstructions = questions["urgent"]?["instructions"]
    {
        // The generator tokenizes the composed state text (long + question).
        let stateText = Schema.stateText(.string(longText), urgentInstructions)
        let ids = engine.ids(stateText)
        check("tokenizer_long.len", ids.count == longSketch["length"]!.intValue)
        check("tokenizer_long.head", Array(ids.prefix(24)) == longSketch["head"]!.intArrayValue)
        check("tokenizer_long.tail", Array(ids.suffix(24)) == longSketch["tail"]?.intArrayValue ?? [])
    }

    // --- 3. encoder embeddings (cosine)
    if case .object(let embRef)? = reference["embeddings"],
       case .array(let embTexts)? = embRef["texts"],
       case .array(let embVectors)? = embRef["vectors"]
    {
        let idLists = embTexts.map { engine.ids($0.stringValue!) }
        let emb = engine.encoder.embedIds(idLists)
        check("embeddings.tokens", idLists.map(\.count).reduce(0, +) == embRef["tokens"]?.intValue)
        for (i, vRef) in embVectors.enumerated() {
            let a = emb[i]
            let b = mlxArray(from: vRef)
            let cos = cosine(a, b)
            check("embedding.cos[\(preview(embTexts[i].stringValue!))]",
                  cos >= 0.9995, String(format: "cos=%.6f", cos))
        }
    }

    // --- 3b. head projections (cosine) for every reference text
    if case .object(let projRef)? = reference["projections"] {
        let texts = reference["tokenizer"]!.objectValue!.keys
        for which in ["state", "action"] {
            guard case .object(let expected)? = projRef[which] else { continue }
            let kind: CLMEngine.HeadKind = which == "state" ? .state : .action
            let vectors = engine.vectorsForParity(texts, kind)
            var minCos = 1.0
            for (i, text) in texts.enumerated() {
                let b = mlxArray(from: expected[text]!)
                let cos = cosine(vectors[i], b)
                minCos = min(minCos, cos)
                check("projection.\(which).cos[\(preview(text))]", cos >= 0.999,
                      String(format: "cos=%.6f", cos))
            }
            print(String(format: "projection[%@] min cos = %.6f", which, minCos))
        }
    }

    // --- 4. full answers vs reference
    // The generator ran its requests on engines with a specific cache state
    // (head engine warmed by the projections pass, tail engine cold). Replicate
    // that so per-request usage.input_tokens is comparable.
    let answerEngine = try await CLMEngine(modelDir: modelDir, cacheSize: 4096, truncation: truncation)
    if truncation == "head", case .object(let tokRefW)? = reference["tokenizer"] {
        let warmTexts = tokRefW.keys
        _ = answerEngine.vectorsForParity(warmTexts, .state)
        _ = answerEngine.vectorsForParity(warmTexts, .action)
    }
    if case .object(let answersRef)? = reference["answers"] {
        var maxProbDelta = 0.0
        var maxScoreDelta = 0.0
        var top1Agreement = 0
        var compared = 0
        for (tag, entryRef) in answersRef.pairs {
            // The generator ran every request on the head engine except
            // long_tail_t1 (tail engine, cold cache). Process only the tags
            // belonging to this run's engine so cache state matches exactly.
            let ranOnThisEngine = truncation == "head" ? tag != "long_tail_t1" : tag == "long_tail_t1"
            if !ranOnThisEngine { continue }
            guard case .object(let entry) = entryRef,
                  let stateKey = entry["state"]?.stringValue,
                  case .array(let qNames)? = entry["questions"],
                  let temperature = entry["temperature"]?.doubleValue
            else { continue }
            var qs = OrderedObject()
            for n in qNames { qs[n.stringValue!] = questions[n.stringValue!]! }
            var stateValue = states[stateKey]!
            if stateKey == "long" {
                guard let longText = inputs["long"]?.stringValue else { continue }
                stateValue = .string(longText)
            }
            let result = try answerEngine.answer(
                state: stateValue, questions: qs, temperature: temperature)
            guard case .object(let refResult)? = entry["result"],
                  case .object(let refAnswers)? = refResult["answers"]
            else { continue }

            for (qid, refAnswer) in refAnswers.pairs {
                guard case .object(let ref) = refAnswer,
                      let gotRaw = result.answers[qid],
                      case .object(let got) = gotRaw
                else { continue }
                if case .string(let refChoice)? = ref["choice"] {
                    compared += 1
                    if case .string(let gotChoice)? = got["choice"], refChoice == gotChoice {
                        top1Agreement += 1
                    }
                }
                if case .object(let refProbs)? = ref["probabilities"],
                   case .object(let gotProbs)? = got["probabilities"]
                {
                    for (k, pv) in refProbs.pairs {
                        let a = pv.doubleValue ?? 0
                        let b = gotProbs[k]?.doubleValue ?? 0
                        maxProbDelta = max(maxProbDelta, abs(a - b))
                    }
                }
                if case .double(let refScore)? = ref["score"],
                   case .double(let gotScore)? = got["score"]
                {
                    maxScoreDelta = max(maxScoreDelta, abs(refScore - gotScore))
                }
                if case .double(let refNoul)? = ref["noul"],
                   case .double(let gotNoul)? = got["noul"]
                {
                    maxProbDelta = max(maxProbDelta, abs(refNoul - gotNoul))
                }
            }
            // usage (cache state matches the generator for these tags)
            if case .object(let refUsage)? = refResult["usage"] {
                let refInput = refUsage["input_tokens"]?.intValue ?? -1
                let gotInput = result.inputTokens
                check("answers[\(tag)].usage.input_tokens", refInput == gotInput,
                      "\(gotInput) vs \(refInput)")
                check("answers[\(tag)].usage.billing_units",
                      refUsage["billing_units"]?.intValue == result.billingUnits)
            }
        }
        print(String(format: "answers: %d compared, top1 %d/%d, maxProbDelta %.5f, maxScoreDelta %.5f",
                     compared, top1Agreement, compared, maxProbDelta, maxScoreDelta))
        check("answers.top1_agreement", compared == 0 || top1Agreement == compared)
        // Deltas come from Metal batch-shape nondeterminism (~5e-4 embedding cos)
        // amplified by the logit scale (100x); the MLX port's own acceptance
        // vs the upstream vLLM server (parity.json) was median 0.036 / p95 0.087.
        check("answers.maxProbDelta", maxProbDelta <= 0.04, String(format: "%.5f", maxProbDelta))
        check("answers.maxScoreDelta", maxScoreDelta <= 0.08, String(format: "%.5f", maxScoreDelta))
    }

    print("----------------------------------------------------------")
    if failures.isEmpty {
        print("PARITY PASS (\(checks) checks)")
        return 0
    }
    print("PARITY FAIL: \(failures.count)/\(checks) checks failed")
    for f in failures.prefix(30) { print("  ✗ \(f)") }
    return 1
}

func preview(_ s: String) -> String {
    let p = String(s.prefix(28)).replacingOccurrences(of: "\n", with: "\\n")
    return p.count < s.count ? p + "…" : p
}

extension JSONValue {
    var arrayValue: [String]? {
        if case .array(let a) = self {
            return a.compactMap(\.stringValue)
        }
        return nil
    }

    var intArrayValue: [Int]? {
        if case .array(let a) = self {
            return a.compactMap { v -> Int? in
                if case .int(let i) = v { return Int(i) }
                return nil
            }
        }
        return nil
    }

    var intValue: Int? {
        if case .int(let i) = self { return Int(i) }
        if case .double(let d) = self { return Int(d) }
        return nil
    }

    var doubleValue: Double? {
        if case .double(let d) = self { return d }
        if case .int(let i) = self { return Double(i) }
        return nil
    }

    var objectValue: OrderedObject? {
        if case .object(let o) = self { return o }
        return nil
    }
}

func cosine(_ a: MLXArray, _ b: MLXArray) -> Double {
    let dot = MLX.sum(a * b).item(Float.self)
    let na = MLX.sqrt(MLX.sum(a * a)).item(Float.self)
    let nb = MLX.sqrt(MLX.sum(b * b)).item(Float.self)
    return Double(dot / (na * nb))
}

func mlxArray(from value: JSONValue) -> MLXArray {
    guard case .array(let items) = value else {
        fatalError("expected array in reference")
    }
    let floats = items.map { item -> Float in
        switch item {
        case .double(let d): return Float(d)
        case .int(let i): return Float(i)
        default: return 0
        }
    }
    return MLXArray(floats, [floats.count])
}
